### ISSUE TITLE
How to publish images as batch?

### ISSUE THREAD

**Issue by CAI23sbP** [GuanSuns/VLMs-Behavior-Critic#1]
How are you @GuanSuns! 
I read your awesome paper.

By the way, could explain or give me a hint about images batch?
I mean "How to send images as batch to GPT4-visoin-preview?".

I knew that how to send video clip to GPT-4V in [this link](https://community.openai.com/t/reading-videos-with-gpt4v/523568), but there was not exist about how to send images as batch.

Did you use 1 batch size?

**Comment by GuanSuns** [comment]
Hi @CAI23sbP,

Thanks for your interest in our work!

For sending images to GPT-4V, I largely followed this tutorial: https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding

Here is the code snippet that I used to set the messages:
```
        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": self.get_text_prompt(task_description),
                    }
                ],
            },
        ]
        for frame in frames:    # base 64 encoded image frames
            frame_message = {
                "type": "image_url",
                "image_url": {
                    "url": f"data:image/jpeg;base64,{frame}",
                    "detail": self.img_detail
                }
            }
            messages[0]['content'].append(frame_message)
```
We will release a more complete reference implementation likely next week.

**Comment by CAI23sbP** [comment]
Thank you for your reply! @GuanSuns.
Your mean that you only sent 1 video per batch to GPT-4v. It is right?
What is index [0] in messages[0]['content'] ? Could you give me a reference or explanation?

**Comment by GuanSuns** [comment]
@CAI23sbP Yes, only 1 video is sent to GPT-4V at a time. I don't think there is a concept of "batch" in OpenAI API (feel free to correct me if I am wrong).

A messages object (a python list) represents a conversation with GPT-4V, and it should save all the messages you sent to GPT-4 and the responses you got back. In our case, we are initializing the conversation so there is only one message (from us). This is why you are seeing messages[0]['content'].

Regarding each item (i.e., each message) in the messages list, it should follow the structure required by OpenAI API. As I mentioned, I am following the format demonstrated in the official example (see the PROMPT_MESSAGES object): https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding.

**Comment by CAI23sbP** [comment]
Oh! i see ! @GuanSuns 
Thank you for your kindness replay~ :>.
