### ISSUE TITLE
OpenAI APIStatusError

### ISSUE THREAD

**Issue by yilin-wu98** [GuanSuns/VLMs-Behavior-Critic#3]
Hi,

I have encountered an issue when using your code to evaluate some of the test video. When I run the first three test cases, the test case 0 and 2 have the correct return. However, the test case 1 will return with the error of "[ERROR] OpenAI model error: APIStatusError.__init__() missing 2 required keyword-only arguments: 'response' and 'body'". I find out that test case 1 contains 22 frames while the other two contains the frames less than 12. After testing, I find that with the number of frames greater than 12, it will have this error. The attached image shows the result of test case 3 which has the 29 frames and returns this error. Do you know what might be the reason for this?
<img width="822" alt="Screenshot 2024-06-10 at 11 47 01 PM" src="https://github.com/GuanSuns/VLMs-Behavior-Critic/assets/46740313/d624e7f0-1733-4196-ab7c-a31f341a8e55">

**Comment by GuanSuns** [comment]
Hi Yilin, can you check your openai package version? 

I just ran the code and did not see the APIStatusError. I am using openai==1.23.6. I also updated the pip requirements file, please pull the latest code. You can do pip install -r requirements.txt .

I will look into this APIStatusError more later.

**Comment by yilin-wu98** [comment]
Hi Guan,

Thanks for your reply. I find out the error message is not very informative. It is actually because of my user tier that causes the requested token exceed my rate limit. After I increase my user tier, it no longer has the error.

**Comment by GuanSuns** [comment]
Cool
