### ISSUE TITLE
Plans to release code for Code as Policies part?

### ISSUE THREAD

**Issue by yilin-wu98** [GuanSuns/VLMs-Behavior-Critic#4]
Dear Author,

I am wondering if you have any plan for open sourcing the Code-as-Policies modules you are using for the VLMs-Behavior-Critic paper. I am curious about the part that you feed the failure explanation into the code-as-policies modules to generate the improved  code for the robot execution. If not, would you mind sharing any prompt template you are using for this code module?

**Comment by GuanSuns** [comment]
Hi Yilin, we might open source the CaP module at a later time, but the code is mostly about connecting high-level APIs to low-level control, and the LLM interface part is relatively simple.  

For code/plan re-generation, we send the critiques to the plan generator via follow-up messages, e.g., `After executing the plan, we've noticed some flaws. Please improve and generate a new plan based on the critique(s) below:`. We also tried directly sending the critiques to the generator without these explanatory words. The results were mostly the same. Note that the ways we tried require the LLM/VLM to support chat mode (i.e., multi-turn conversation). In the paper, we only used GPT-4V as plan generator.
